FF.F...FF.FFFF.F.F.FF
======================================================================
FAIL: test_base_case_2 (__main__.SieveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '2 is prime\nNumber of filters = -1' != '2 is prime\nNumber of filters = 0'
  2 is prime
- Number of filters = -1?                     ^^
+ Number of filters = 0?                     ^


======================================================================
FAIL: test_base_case_3 (__main__.SieveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '3 is prime\nNumber of filters = -1' != '3 is prime\nNumber of filters = 0'
  3 is prime
- Number of filters = -1?                     ^^
+ Number of filters = 0?                     ^


======================================================================
FAIL: test_cube (__main__.SieveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '1331 is not the product of two primes\nNumber of filters = 5' != '1331 is not the product of two primes\nNumber of filters = 4'
  1331 is not the product of two primes
- Number of filters = 5?                     ^
+ Number of filters = 4?                     ^


======================================================================
FAIL: test_exactly_2_primes (__main__.SieveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '69 3 23\nNumber of filters = 5' != '69 3 23\nNumber of filters = 4'
  69 3 23
- Number of filters = 5?                     ^
+ Number of filters = 4?                     ^


======================================================================
FAIL: test_exactly_2_primes_diff (__main__.SieveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '205 5 41\nNumber of filters = 8' != '205 5 41\nNumber of filters = 6'
  205 5 41
- Number of filters = 8?                     ^
+ Number of filters = 6?                     ^


======================================================================
FAIL: test_large_prime (__main__.SieveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '9901 is prime\nNumber of filters = 48' != '9901 is prime\nNumber of filters = 25'
  9901 is prime
- Number of filters = 48?                     ^^
+ Number of filters = 25?                     ^^


======================================================================
FAIL: test_many_filters (__main__.SieveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '3722 2 1861\nNumber of filters = 31' != '3722 2 1861\nNumber of filters = 18'
  3722 2 1861
- Number of filters = 31?                     -
+ Number of filters = 18?                      +


======================================================================
FAIL: test_many_many_filters (__main__.SieveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '205193 449 457\nNumber of filters = 227' != '205193 449 457\nNumber of filters = 87'
  205193 449 457
- Number of filters = 227?                     ^^
+ Number of filters = 87?                     ^


======================================================================
FAIL: test_perfect_square_of_primes (__main__.SieveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '169 13 13\nNumber of filters = 6' != '169 13 13\nNumber of filters = 5'
  169 13 13
- Number of filters = 6?                     ^
+ Number of filters = 5?                     ^


======================================================================
FAIL: test_prime_diff (__main__.SieveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '263 is prime\nNumber of filters = 7' != '263 is prime\nNumber of filters = 6'
  263 is prime
- Number of filters = 7?                     ^
+ Number of filters = 6?                     ^


======================================================================
FAIL: test_square_and_smaller_1183 (__main__.SieveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '1183 is not the product of two primes\nNumber of filters = 6' != '1183 is not the product of two primes\nNumber of filters = 5'
  1183 is not the product of two primes
- Number of filters = 6?                     ^
+ Number of filters = 5?                     ^


======================================================================
FAIL: test_three_prime_factors (__main__.SieveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '646 is not the product of two primes\nNumber of filters = 8' != '646 is not the product of two primes\nNumber of filters = 6'
  646 is not the product of two primes
- Number of filters = 8?                     ^
+ Number of filters = 6?                     ^


======================================================================
FAIL: test_too_many_filters (__main__.SieveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 193, in _t
    self.assertEqual(returncode, expected_status)
AssertionError: 0 != 2

----------------------------------------------------------------------
Ran 21 tests in 0.300s

FAILED (failures=13)
