..F.F.F..
======================================================================
FAIL: test_mixed_arg_78a (__main__.ArgumentsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 184, in _t
    self.assertEqual(stderr, expected_stderr)
AssertionError: '' != 'Usage:\n\tpfact n'
+ Usage:
+ 	pfact n

======================================================================
FAIL: test_non_integer_arg (__main__.ArgumentsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 184, in _t
    self.assertEqual(stderr, expected_stderr)
AssertionError: '' != 'Usage:\n\tpfact n'
+ Usage:
+ 	pfact n

======================================================================
FAIL: test_space_in_arg (__main__.ArgumentsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 184, in _t
    self.assertEqual(stderr, expected_stderr)
AssertionError: '' != 'Usage:\n\tpfact n'
+ Usage:
+ 	pfact n

----------------------------------------------------------------------
Ran 9 tests in 0.009s

FAILED (failures=3)
